In [71]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import math

In [89]:
x = [2,4,6,8,10,12,14,16,18,20]
y = [0,0,0,0,0,0,1,1,1,1]
X = pd.DataFrame(x)
Y = pd.DataFrame(y)

## Sklearn 을 이용한 Logistic Regression

In [123]:
model = LogisticRegression(C=1000, 
                   random_state=0)

In [124]:
model.fit(X,Y)

/Users/Keith/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(C=1000, random_state=0)

In [125]:
model.coef_

array([[5.8332926 , 0.00649951]])

In [126]:
model.intercept_

array([-75.83965789])

In [127]:
model.predict(X)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

## 직접 구현한 Logistic Regression

In [90]:
X[1] = np.ones(len(x), dtype = int)

In [91]:
w = np.empty(X.shape[1])

In [92]:
w.fill(0)

In [128]:
W = pd.DataFrame(w)

In [121]:
learning_rate = 0.01

In [104]:
test_num = 1000

In [129]:
for i in range(test_num):
    sigmoid = 1 / (1 + np.exp(-X.dot(W)))
    W = W - ((sigmoid - Y).T.dot(X) * learning_rate / len(X)).T
    print("test_num : ", i)
    print("slope : ",W.iloc[0])
    print("y-intercept : ",W.iloc[1])

test_num :  0
slope :  0    0.013
Name: 0, dtype: float64
y-intercept :  0   -0.001
Name: 1, dtype: float64
test_num :  1
slope :  0    0.021041
Name: 0, dtype: float64
y-intercept :  0   -0.002354
Name: 1, dtype: float64
test_num :  2
slope :  0    0.026081
Name: 0, dtype: float64
y-intercept :  0   -0.003922
Name: 1, dtype: float64
test_num :  3
slope :  0    0.02929
Name: 0, dtype: float64
y-intercept :  0   -0.005621
Name: 1, dtype: float64
test_num :  4
slope :  0    0.031368
Name: 0, dtype: float64
y-intercept :  0   -0.007401
Name: 1, dtype: float64
test_num :  5
slope :  0    0.032737
Name: 0, dtype: float64
y-intercept :  0   -0.00923
Name: 1, dtype: float64
test_num :  6
slope :  0    0.03366
Name: 0, dtype: float64
y-intercept :  0   -0.011091
Name: 1, dtype: float64
test_num :  7
slope :  0    0.034299
Name: 0, dtype: float64
y-intercept :  0   -0.012972
Name: 1, dtype: float64
test_num :  8
slope :  0    0.034758
Name: 0, dtype: float64
y-intercept :  0   -0.014864
Name: 1

Name: 1, dtype: float64
test_num :  147
slope :  0    0.053987
Name: 0, dtype: float64
y-intercept :  0   -0.27159
Name: 1, dtype: float64
test_num :  148
slope :  0    0.054117
Name: 0, dtype: float64
y-intercept :  0   -0.27337
Name: 1, dtype: float64
test_num :  149
slope :  0    0.054246
Name: 0, dtype: float64
y-intercept :  0   -0.27515
Name: 1, dtype: float64
test_num :  150
slope :  0    0.054376
Name: 0, dtype: float64
y-intercept :  0   -0.276929
Name: 1, dtype: float64
test_num :  151
slope :  0    0.054506
Name: 0, dtype: float64
y-intercept :  0   -0.278706
Name: 1, dtype: float64
test_num :  152
slope :  0    0.054635
Name: 0, dtype: float64
y-intercept :  0   -0.280483
Name: 1, dtype: float64
test_num :  153
slope :  0    0.054765
Name: 0, dtype: float64
y-intercept :  0   -0.282259
Name: 1, dtype: float64
test_num :  154
slope :  0    0.054894
Name: 0, dtype: float64
y-intercept :  0   -0.284034
Name: 1, dtype: float64
test_num :  155
slope :  0    0.055023
Name: 0, dty

y-intercept :  0   -0.482138
Name: 1, dtype: float64
test_num :  270
slope :  0    0.069484
Name: 0, dtype: float64
y-intercept :  0   -0.483809
Name: 1, dtype: float64
test_num :  271
slope :  0    0.069606
Name: 0, dtype: float64
y-intercept :  0   -0.48548
Name: 1, dtype: float64
test_num :  272
slope :  0    0.069729
Name: 0, dtype: float64
y-intercept :  0   -0.48715
Name: 1, dtype: float64
test_num :  273
slope :  0    0.069851
Name: 0, dtype: float64
y-intercept :  0   -0.488819
Name: 1, dtype: float64
test_num :  274
slope :  0    0.069973
Name: 0, dtype: float64
y-intercept :  0   -0.490487
Name: 1, dtype: float64
test_num :  275
slope :  0    0.070095
Name: 0, dtype: float64
y-intercept :  0   -0.492154
Name: 1, dtype: float64
test_num :  276
slope :  0    0.070217
Name: 0, dtype: float64
y-intercept :  0   -0.493821
Name: 1, dtype: float64
test_num :  277
slope :  0    0.070339
Name: 0, dtype: float64
y-intercept :  0   -0.495486
Name: 1, dtype: float64
test_num :  278
slope

test_num :  424
slope :  0    0.087634
Name: 0, dtype: float64
y-intercept :  0   -0.731331
Name: 1, dtype: float64
test_num :  425
slope :  0    0.087748
Name: 0, dtype: float64
y-intercept :  0   -0.732877
Name: 1, dtype: float64
test_num :  426
slope :  0    0.087861
Name: 0, dtype: float64
y-intercept :  0   -0.734421
Name: 1, dtype: float64
test_num :  427
slope :  0    0.087975
Name: 0, dtype: float64
y-intercept :  0   -0.735965
Name: 1, dtype: float64
test_num :  428
slope :  0    0.088088
Name: 0, dtype: float64
y-intercept :  0   -0.737508
Name: 1, dtype: float64
test_num :  429
slope :  0    0.088201
Name: 0, dtype: float64
y-intercept :  0   -0.73905
Name: 1, dtype: float64
test_num :  430
slope :  0    0.088315
Name: 0, dtype: float64
y-intercept :  0   -0.740592
Name: 1, dtype: float64
test_num :  431
slope :  0    0.088428
Name: 0, dtype: float64
y-intercept :  0   -0.742132
Name: 1, dtype: float64
test_num :  432
slope :  0    0.088541
Name: 0, dtype: float64
y-intercep

test_num :  522
slope :  0    0.09851
Name: 0, dtype: float64
y-intercept :  0   -0.879191
Name: 1, dtype: float64
test_num :  523
slope :  0    0.098618
Name: 0, dtype: float64
y-intercept :  0   -0.880663
Name: 1, dtype: float64
test_num :  524
slope :  0    0.098727
Name: 0, dtype: float64
y-intercept :  0   -0.882135
Name: 1, dtype: float64
test_num :  525
slope :  0    0.098835
Name: 0, dtype: float64
y-intercept :  0   -0.883606
Name: 1, dtype: float64
test_num :  526
slope :  0    0.098943
Name: 0, dtype: float64
y-intercept :  0   -0.885076
Name: 1, dtype: float64
test_num :  527
slope :  0    0.099052
Name: 0, dtype: float64
y-intercept :  0   -0.886545
Name: 1, dtype: float64
test_num :  528
slope :  0    0.09916
Name: 0, dtype: float64
y-intercept :  0   -0.888014
Name: 1, dtype: float64
test_num :  529
slope :  0    0.099268
Name: 0, dtype: float64
y-intercept :  0   -0.889482
Name: 1, dtype: float64
test_num :  530
slope :  0    0.099376
Name: 0, dtype: float64
y-intercept

Name: 1, dtype: float64
test_num :  677
slope :  0    0.11473
Name: 0, dtype: float64
y-intercept :  0   -1.099166
Name: 1, dtype: float64
test_num :  678
slope :  0    0.114831
Name: 0, dtype: float64
y-intercept :  0   -1.100533
Name: 1, dtype: float64
test_num :  679
slope :  0    0.114932
Name: 0, dtype: float64
y-intercept :  0   -1.1019
Name: 1, dtype: float64
test_num :  680
slope :  0    0.115032
Name: 0, dtype: float64
y-intercept :  0   -1.103266
Name: 1, dtype: float64
test_num :  681
slope :  0    0.115133
Name: 0, dtype: float64
y-intercept :  0   -1.104631
Name: 1, dtype: float64
test_num :  682
slope :  0    0.115234
Name: 0, dtype: float64
y-intercept :  0   -1.105996
Name: 1, dtype: float64
test_num :  683
slope :  0    0.115335
Name: 0, dtype: float64
y-intercept :  0   -1.10736
Name: 1, dtype: float64
test_num :  684
slope :  0    0.115435
Name: 0, dtype: float64
y-intercept :  0   -1.108724
Name: 1, dtype: float64
test_num :  685
slope :  0    0.115536
Name: 0, dtyp

test_num :  787
slope :  0    0.125568
Name: 0, dtype: float64
y-intercept :  0   -1.245854
Name: 1, dtype: float64
test_num :  788
slope :  0    0.125665
Name: 0, dtype: float64
y-intercept :  0   -1.247154
Name: 1, dtype: float64
test_num :  789
slope :  0    0.125761
Name: 0, dtype: float64
y-intercept :  0   -1.248454
Name: 1, dtype: float64
test_num :  790
slope :  0    0.125857
Name: 0, dtype: float64
y-intercept :  0   -1.249753
Name: 1, dtype: float64
test_num :  791
slope :  0    0.125953
Name: 0, dtype: float64
y-intercept :  0   -1.251051
Name: 1, dtype: float64
test_num :  792
slope :  0    0.126049
Name: 0, dtype: float64
y-intercept :  0   -1.252349
Name: 1, dtype: float64
test_num :  793
slope :  0    0.126145
Name: 0, dtype: float64
y-intercept :  0   -1.253646
Name: 1, dtype: float64
test_num :  794
slope :  0    0.12624
Name: 0, dtype: float64
y-intercept :  0   -1.254942
Name: 1, dtype: float64
test_num :  795
slope :  0    0.126336
Name: 0, dtype: float64
y-intercep